# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 765bfc4407d505ca8ee1b59570e2e0d03a7b1831e25a18ba398e1cb6aebfde8cb1e71958ac99cc778b5f0fdf083fbfe469d74ece6ca2b083d456bc233802b7a0

test:
  secret_key_base: b10ce3fe9f764d86384edb61c1d8bdfad8ef9edcf033a95e59bbf3d0d580a0f3a86f195cca8e7e8ea50f2e8347faa1edf358bc55f0eedb0ef8960b74e3e2fa15

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
